Resources:
  Function:
    Type: AWS::Serverless::Function
    Properties:
      Timeout: 5
      MemorySize: 128
      Handler: app.lambda_handler
      CodeUri: C:\Users\alex\PycharmProjects\aws_cm_intern\app
      Runtime: python3.8